### ISSUE TITLE
POST confidential note - company is disabled error

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#11]
When posting a note (confidential), a `company is disabled` error is returned.  TASS API f753090311ccbeb6403bb903a387a6d1ce3731e4 (updated 2024-12-06)

```
json.dumps(new_note)='{"note_cat": "GEN", "note_date": "2024-12-06T01:33:04.813Z", "note_text": "A note created using the new TASS API."}'
@request at 2024-12-06T11:33:04.814165
@request.args: ('emp_code/notes/confidential',)
@request.kwargs:
{'json': {'note_cat': 'GEN',
          'note_date': '2024-12-06T01:33:04.813Z',
          'note_text': 'A note created using the new TASS API.'}}
{'User-Agent': 'example/api-beta/v1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Authorization': 'Bearer sanitized'}
@parse_kwargs.kwargs={'json': {'note_cat': 'GEN', 'note_date': '2024-12-06T01:33:04.813Z', 'note_text': 'A note created using the new TASS API.'}}
@request processed URL: https://tass-test.example.org/api/01/employee/emp_code/notes/confidential
@request.request_kwargs={'json': {'note_cat': 'GEN', 'note_date': '2024-12-06T01:33:04.813Z', 'note_text': 'A note created using the new TASS API.'}}
@parse_response.headers=
{'Cache-Control': 'no-cache,no-store', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 06 Dec 2024 01:33:14 GMT'}
Traceback (most recent call last):
  File "/Users/redtrinity/Desktop/./tass_api_beta.py", line 56, in <module>
    r = cnotes.add_note("emp_code", json=new_note)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/redtrinity/Library/Python/site-packages/tassbeta/endpoints/employees.py", line 92, in add_note
    return self.post(f"{emp_code}/{self.sub_endpoint}", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/redtrinity/Library/Python/site-packages/tassbeta/decorators.py", line 70, in wrapped
    return parse_response(r=resp, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/redtrinity/Library/Python/site-packages/tassbeta/utils/__init__.py", line 234, in parse_response
    parse_response_errors(r)
  File "/Users/redtrinity/Library/Python/site-packages/tassbeta/utils/__init__.py", line 204, in parse_response_errors
    raise APIResponseException(msg)
tassbeta.api_exceptions.APIResponseException: Error (status 400): Validation errors have occurred. 
cmpy_code: ['Company is disabled.']
```

**Comment by redtrinity** [comment]
This also occurs when posting a standard note.

**Comment by scottetass** [comment]
Hi,

This error should be fixed in the next build.

Thanks, Scott
