### ISSUE TITLE
Issue: HTTP 500 errors when attempting PATCH

### ISSUE THREAD

**Issue by redtrinity** [TheAlphaSchoolSystemPTYLTD/APIBetaTesting#6]
When attempting to `PATCH` an employee record, an HTTP 500 error is returned.
Note, the data and server in this output has been sanitised.

An authentication token has been successfully granted, and full permisions for the `employee` endpoint have been set for the API user.

This error occurs when using `/add1_text` as the path (first output) as well as when using `add1_text` as the path (second output).

What's being used:
- Python v3.12.6
- requests v2.32.0

Session headers:

```
{
    'User-Agent': 'sanitised',
    'Accept-Encoding': 'gzip, deflate',
    'Accept': 'application/json',
    'Connection': 'keep-alive',
    'Content-Type': 'application/json',
    'Authorization': 'Bearer sanitised'
}
```

Notes:
WIth the `requests` package for Python, when using the `params`, `json`, or `data` arguments for `request.patch`, it converts the native Python dictionary data type to the expected format for the request, for example, the data provided to `params` gets converted into a parameterised url, when data is provided to `json` the dictionary is converted to a JSON string, and when `data` is used, the dictionary is converted into a `POST` style body.

The `requests` package should also be setting the `Content-Type` header to `application/json` (however I've explicitly set this header for all requests).

```
[redtrinity@macos]:Desktop # ./tass_api_beta.py
@request args=('1010101/information',), kwargs={'params': {'op': 'replace', 'path': '/add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information?op=replace&path=%2Fadd1_text&value=New+Value'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:10:12 GMT'}
None
@request args=('1010101/information',), kwargs={'json': {'op': 'replace', 'path': '/add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:10:12 GMT'}
None
@request args=('1010101/information',), kwargs={'data': {'op': 'replace', 'path': '/add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:10:12 GMT'}
None
```

```
[redtrinity@macos]:Desktop # ./tass_api_beta.py
@request args=('1010101/information',), kwargs={'params': {'op': 'replace', 'path': 'add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information?op=replace&path=add1_text&value=New+Value'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:09:42 GMT'}
None
@request args=('1010101/information',), kwargs={'json': {'op': 'replace', 'path': 'add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:09:42 GMT'}
None
@request args=('1010101/information',), kwargs={'data': {'op': 'replace', 'path': 'add1_text', 'value': 'New Value'}}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:09:42 GMT'}
None
```

**Comment by redtrinity** [comment]
Audit logs:

`params` argument method:
```
500	PATCH	/01/employee/[redacted]/information	Object reference not set to an instance of an object.	   at TASS.API.Web.Middleware.UpdateRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\UpdateRestrictionsMiddleware.cs:line 66    at TASS.API.Web.Middleware.CompanyCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService, IDiagnosticContext diagnosticContext) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\CompanyCheckMiddleware.cs:line 36    at TASS.API.Web.Middleware.ViewRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\ViewRestrictionsMiddleware.cs:line 95    at TASS.API.Web.Middleware.PermissionCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\PermissionCheckMiddleware.cs:line 44    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

`json` argument method:
```
500	PATCH	/01/employee/[redacted]/information	The JSON patch document was malformed and could not be parsed.	   at Microsoft.AspNetCore.JsonPatch.Converters.JsonPatchDocumentConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)    at TASS.API.Web.Middleware.UpdateRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\UpdateRestrictionsMiddleware.cs:line 66    at TASS.API.Web.Middleware.CompanyCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService, IDiagnosticContext diagnosticContext) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\CompanyCheckMiddleware.cs:line 36    at TASS.API.Web.Middleware.ViewRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\ViewRestrictionsMiddleware.cs:line 95    at TASS.API.Web.Middleware.PermissionCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\PermissionCheckMiddleware.cs:line 44    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

`data` argument method:
```
500	PATCH	/01/employee/[redacted]/information	Unexpected character encountered while parsing value: o. Path '', line 0, position 0.	   at Newtonsoft.Json.JsonTextReader.ParseValue()    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)    at TASS.API.Web.Middleware.UpdateRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\UpdateRestrictionsMiddleware.cs:line 66    at TASS.API.Web.Middleware.CompanyCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService, IDiagnosticContext diagnosticContext) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\CompanyCheckMiddleware.cs:line 36    at TASS.API.Web.Middleware.ViewRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\ViewRestrictionsMiddleware.cs:line 95    at TASS.API.Web.Middleware.PermissionCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\PermissionCheckMiddleware.cs:line 44    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by redtrinity** [comment]
This also seems to happen when sending the literal JSON string regardless of `path` starting with a `/` or not.

```
@request args=('1010101/information',), kwargs={'json': "{'op':'replace','path':'/add1_text','value':'New Value'}"}
{'User-Agent': 'redlands/api-beta/v1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer redacted'}
@request url='https://tass-test.sanitised.example/api/01/employee/1010101/information'
HTTP 500 Internal Server Error while performing 'PATCH' 'https://tass-test.sanitised.example/api/01/employee/1010101/information'
{'Transfer-Encoding': 'chunked', 'Server': 'Microsoft-IIS/10.0', 'X-Powered-By': 'ASP.NET', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Date': 'Fri, 29 Nov 2024 04:49:51 GMT'}
```

```
500	PATCH	/01/employee/[redacted]/information	The JSON patch document was malformed and could not be parsed.	   at Microsoft.AspNetCore.JsonPatch.Converters.JsonPatchDocumentConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)    at TASS.API.Web.Middleware.UpdateRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\UpdateRestrictionsMiddleware.cs:line 66    at TASS.API.Web.Middleware.CompanyCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService, IDiagnosticContext diagnosticContext) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\CompanyCheckMiddleware.cs:line 36    at TASS.API.Web.Middleware.ViewRestrictionsMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\ViewRestrictionsMiddleware.cs:line 95    at TASS.API.Web.Middleware.PermissionCheckMiddleware.InvokeAsync(HttpContext context, ISecurityUser user, IIdentityService identityService) in D:\jenkins\workspace\tassapi_master\TASS.API.Web\Middleware\PermissionCheckMiddleware.cs:line 44    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by scottetass** [comment]
Hi,

Can you please check that the JSON being sent is an array? It needs to be an array, even if there is only one item being sent. I think it just needs the square brackets around the JSON like below:

`kwargs={ 'json': "[ {'op':'replace','path':'/add1_text','value':'New Value'} ]" }`

Thanks, Scott

**Comment by redtrinity** [comment]
Well that's only slightly embarrasing - it might help if I put the glasses on! The documentation does clearly indicate it's a JSON array which makes sense because each attribute being changed needs to be in the array for parsing on the server side.
